# Site Settings
title: David Gautier Resume
url: 'https://dgautier.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: David Gautier
tagline: Back End Architect & Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am an Architect/Developer, specialized in designing and implementing Java JEE ECM/BPM solutions.
 I have worked 9 years on various ECM/BPM projects mostly for insurances and banking companies. I work to ensure
 our common base code remains <a href="#" target="https://fr.wikipedia.org/wiki/Principe_KISS">KISS</a> friendly while trying to secure, automate and simplify code and deployments. I aim
  to become a true Software Craftsman.'

#sidebar links
email: david.gautier@ginko.io
phone: 06 85 67 28 18
website: ginko.io #do not add http://
linkedin: dgautier1
github: dgautier
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
